### ISSUE TITLE
FormModalPage  behaves weird

### ISSUE THREAD

**Issue by Sheryorov** [commercetools/ui-kit#1418] opened 2020-07-06 11:14 UTC
I add to my project and it behaves weird. See: https://gifyu.com/image/QExS
Some times modal not fixed in visible area

Code:
```
`<Spacings.Inset>
      {showSpinner ? <LoadingSpinner size="s">Loading</LoadingSpinner> : null}
      <Text.Headline as="h2">Test</Text.Headline>
      {
        array.map((item, idx) => {
          // Some actions
          return <div style={{ margin: "20px 0" }} key={idx}>
            <CollapsiblePanel header={idx} isDefaultClosed={true}>
              <Card>
                <div style={{ display: "flex", padding: "10px 0" }}>
                  <div className="container" style={{ paddingRight: "10px" }}>
                       // some data
```
                  </div>
                  <div className="container" style={{ paddingRight: "10px" }}>
                    <center>
                        //some data
                    </center>

                  </div>
                </div>
              </Card>
              <div style={{ width: "100%", margin: "10px 0", background: '#fff' }}>
                <Table
                  columns={columnsDefinition}
                  rows={newItems}
                />
              </div>
            </CollapsiblePanel>
          </div>
        })
      }
      {
        condition? ?
          <FormModalPage
            title="Return Info"
            isOpen={modalOpen}
            onClose={() => setModalOpen(false)}
            topBarPreviousPathLabel="test Requests"
            topBarCurrentPathLabel={"test"}
            onSecondaryButtonClick={() => setModalOpen(false)}
            onPrimaryButtonClick={() => console.log('confirm')}
          >
            <TextField
              title="Internal commit"
              value=""
              onChange={evt => { }}
            />
            <p>Refund Value</p>
            <LocalizedMoneyInput
              selectedCurrency={returnOrderItem?.currencyCode}
              value={{
                [returnOrderItem?.currencyCode]:
                {
                  currencyCode: returnOrderItem?.currencyCode,
                  amount: `${returnOrderItem?.obj?.value?.refundAmount}`
                }
              }}
              onChange={evt => { }}
            />
          </FormModalPage>
          : null
      }
    </Spacings.Inset >`

deps:

>  "@commercetools-frontend/actions-global": "16.8.0",
    "@commercetools-frontend/application-components": "^16.8.0",
    "@commercetools-frontend/application-shell": "16.8.0",
    "@commercetools-frontend/application-shell-connectors": "16.8.0",
    "@commercetools-frontend/assets": "16.8.0",
    "@commercetools-frontend/i18n": "16.8.0",
    "@commercetools-frontend/mc-http-server": "16.8.1",
    "@commercetools-frontend/permissions": "16.8.0",
    "@commercetools-frontend/ui-kit": "^10.22.2",
    "@commercetools-uikit/card": "^10.18.4",
    "@commercetools-uikit/collapsible-panel": "^10.18.4",
    "@commercetools-uikit/data-table": "^10.18.4",
    "@commercetools-uikit/flat-button": "10.18.4",
    "@commercetools-uikit/icons": "10.18.4",
    "@commercetools-uikit/spacings": "10.18.4",
    "@commercetools-uikit/text": "10.18.4",
    "apollo-client": "2.6.8",
    "aws4": "^1.9.1",
    "aws4-axios": "^1.12.0",
    "axios": "^0.18.1",
    "crypto": "^1.0.1",
    "deploy-aws-s3-cloudfront": "^3.2.3",
    "dinero.js": "^1.8.1",
    "hex-to-uuid": "^1.0.1",
    "moment": "^2.25.3",
    "prop-types": "15.7.2",
    "react": "16.13.1",
    "react-apollo": "3.1.5",
    "react-dom": "16.13.1",
    "react-intl": "3.4.0",
    "react-redux": "7.2.0",
    "react-router-dom": "5.1.2",
    "redux": "4.0.5"
  },
  "devDependencies": {
    "@commercetools-frontend/jest-preset-mc-app": "16.8.2",
    "@commercetools-frontend/mc-scripts": "^16.12.0",
    "@testing-library/react": "10.0.4",
    "enzyme": "3.11.0",
    "jest": "26.0.1"
  }

**Comment by emmenko** [comment] 2020-07-06 11:42
Hmm that's a weird behavior. Thanks for reporting it.

Can you inspect the CSS and see what might cause the issue?
Also, which browser are you using? Is it the same in the other browsers?

**Comment by Sheryorov** [comment] 2020-07-06 11:47
See: https://gifyu.com/image/QExS
Some times modal not fixed in visible area

**Comment by emmenko** [comment] 2020-07-06 11:51
Yes I saw that, I'm asking if you have tried to look at the CSS to see what the issue could be, and if the issue is consistent across different browsers.

You can image it's a bit hard for us to tell what the issue is by looking at a video.

If you can manage to provide a reproduction case for us to look at, that would be even better (for example trying to reproduce it in a codesandbox: https://codesandbox.io/s/commercetools-ui-kit-codesandbox-1vz7c) 🙂

Thanks

**Comment by Sheryorov** [comment] 2020-07-06 11:58
See: https://gifyu.com/image/QEwN.

I just remove and back app container in console, its works.

**Comment by Sheryorov** [comment] 2020-07-06 11:59
is it maybe problem with styles?

**Comment by Sheryorov** [comment] 2020-07-06 12:43
https://codesandbox.io/s/silly-lovelace-xsgem?file=/src/App.js

**Comment by Sheryorov** [comment] 2020-07-07 06:32
I figure out why is behaves like that,  when we have many CollapsiblePanel item and we open one of them it behaves weird, because height of component changes

**Comment by emmenko** [comment] 2020-07-07 09:45
Thanks for the codesandbox. However, I realized it's not very helpful because we need to test/reproduce this within the application layout.

I have the feeling though that because the page scrolls, the overlay of the modal scrolls with, which makes it look like it's broken.

I'll see if I can manage to reproduce this in a simpler setup.

**Comment by Sheryorov** [comment] 2020-07-08 09:43
@emmenko  Can you reproduce it?

**Comment by anilkk** [comment] 2020-09-07 22:47
@Sheryorov: Just want to follow up,  Do you still have this issue?

**Comment by Sheryorov** [comment] 2020-09-09 11:12
> @Sheryorov: Just want to follow up, Do you still have this issue?

Yes, i do

**Comment by anilkk** [comment] 2020-09-12 23:31
@Sheryorov  Thanks for the update. 

Your previously shared **codesandbox** example doesn't work.
https://codesandbox.io/s/silly-lovelace-xsgem?file=/src/App.js

It would be nice if you can describe detailed steps to reproduce this issue.

**Comment by emmenko** [comment] 2021-02-02 09:20
I believe the issue is how/where the component is rendered.

You should render this once somewhere in the main page layout, so that the elements are correctly stacked. Usually, the rendering of this component is route driven.
For example, if you render a list or something, you shouldn't render this component for each list item.

Closing this, as there is nothing here in uikit that we can do about it.

**Closed by emmenko** 2021-02-02 09:20 UTC
Labels: ❓ Type: Question, 🐛 Type: Bug, 📞 Type: Customer request
